name: Trigger auto deployment for apkaupload

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/apkaupload-AutoDeployTrigger-0bd598a3-6bb4-460e-9f99-4d89087af811.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.APKAUPLOAD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APKAUPLOAD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APKAUPLOAD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: notyfikator2.azurecr.io
          registryUsername: ${{ secrets.APKAUPLOAD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APKAUPLOAD_REGISTRY_PASSWORD }}
          containerAppName: apkaupload
          resourceGroup: Projekt2
          imageToBuild: notyfikator2.azurecr.io/apkaupload:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


