name: Trigger auto deployment for webapp123

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/webapp123-AutoDeployTrigger-b04f539f-0cf9-4edb-b225-956265068004.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WEBAPP123_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WEBAPP123_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WEBAPP123_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: notyfikator2.azurecr.io
          registryUsername: ${{ secrets.WEBAPP123_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WEBAPP123_REGISTRY_PASSWORD }}
          containerAppName: webapp123
          resourceGroup: DefaultResourceGroup-NEU
          imageToBuild: notyfikator2.azurecr.io/webapp123:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


